[package]
name = "yarms-packet"
version = "0.1.0"
edition.workspace = true
description = "Minecraft packet definitions."

[dependencies]
yarms-protocol = { path = "../yarms-protocol", default-features = false }

bytes = { version = "1.10.0", default-features = false }

[lints]
workspace = true