[package]
name = "yarms-identifier"
version = "0.1.0"
edition.workspace = true
description = "Minecraft identifiers, ex. `minecraft:stone`."

[lints]
workspace = true

[features]
default = [ "std" ]
std = []